### PR TITLE
3.0.1

### PR DESCRIPTION
**Pull request by johnmgriffith**
Bug fixes on icons:

bounding boxes added to halftone icons
16px magnifying glass icons filling in circles
eyedropper-32's svg bounding box appearing black
paths updated for filter-16 24 and 32, flash-16, folder-new-16, graph-moving-average-16, layer-polygon-24 and 32, and layer-polygon-service-24 and 32

### CODE REVIEW

**Comment by johnmgriffith** [comment]
Bug fixes on icons:

• bounding box paths added to halftone icons
• eyedropper-32 bounding box missing `fill="none"` in svg code
• additional path updates:

  | icon names
-- | --
1 | magnifying-glass-16
2 | magnifying-glass-plus-16
3 | magnifying-glass-minus-16
4 | filter-16
5 | filter-24
6 | filter-32
7 | flash-16
8 | folder-new-16
9 | graph-moving-average-16
10 | layer-polygon-24
11 | layer-polygon-32
12 | layer-polygon-service-24
13 | layer-polygon-service-32
14 | a-z-down-24
15 | a-z-up-24
16 | applications-32
17 | color-coded-map-16
18 | color-coded-map-24
19 | color-coded-map-32
20 | deep-learning-16
21 | zoom-to-object-16

**Comment by johnmgriffith** [comment]
Sweet! Merging now, then releasing 3.0.1

**Comment by paulcpederson** [comment]
@johnmgriffith the correct version number would be `3.0.0-beta.2` I think

**Comment by johnmgriffith** [comment]
Ah, okay. I'll make the edit.

**Pull request merged**
