### PR TITLE
2.5.3

### PR DESCRIPTION
**Pull request by johnmgriffith**
New icons:

• boolean
• integer
• string

### CODE REVIEW

**Comment by paulcpederson** [comment]
:+1:

**Comment by johnmgriffith** [comment]
Let's hold off on merging until I get verification from Alan. He's still reviewing the concepts with his team

**Comment by asangma** [comment]
G2G

**Comment by asangma** [comment]
Thanks y'all!

**Comment by johnmgriffith** [comment]
Total is now 8 icons:

• boolean
• integer
• string
• number
• color-correction
• footprint
• overview
• seamlines

**Pull request merged**
