### PR TITLE
3.16.2

### PR DESCRIPTION
**Pull request by KatelynSeitz**
added toggle icons

image

### CODE REVIEW

**Comment by julio8a** [comment]
What's the use case and need for these?

**Comment by KatelynSeitz** [comment]
@julio8a I had the same question since we have toggle components in Calcite. To my understanding, they are not interactive for their use-case in Field Maps, where they are used in forms to indicate the input type available here:

MicrosoftTeams-image

@TheBlueDog

**Comment by paulcpederson** [comment]
using an icon that looks exactly like an interactive element does seem like it could lead to confusion...

**Review by TheBlueDog — APPROVED** [review]
Icons appear as requested.

**Review by paulcpederson — APPROVED** [review]

**Review by julio8a — APPROVED** [review]

**Review by allieorth — APPROVED** [review]

**Pull request merged**
