### PR TITLE
3.22.3

### PR DESCRIPTION
**Pull request by nicklu10**
**added:**

joined-view-layer-24
joined-view-layer-32
joined-view-layer-16
number-circle-1-f-16
number-circle-1-f-24
number-circle-1-f-32
number-circle-2-f-16
number-circle-2-f-24
number-circle-2-f-32
number-circle-3-f-16
number-circle-3-f-24
number-circle-3-f-32
number-circle-4-f-16
number-circle-4-f-24
number-circle-4-f-32
number-circle-5-f-16
number-circle-5-f-24
number-circle-5-f-32
number-circle-6-f-16
number-circle-6-f-24
number-circle-6-f-32
number-circle-7-f-16
number-circle-7-f-24
number-circle-7-f-32
number-circle-8-f-16
number-circle-8-f-24
number-circle-8-f-32
number-circle-9-f-16
number-circle-9-f-24
number-circle-9-f-32
location-sharing-disabled-16
location-sharing-disabled-24
location-sharing-disabled-32
location-sharing-enabled-16
location-sharing-enabled-24
location-sharing-enabled-32
location-sharing-filled-16
location-sharing-filled-24
location-sharing-filled-32

Screenshot 2023-05-05 at 12 33 13 PM

### CODE REVIEW

**Review by allieorth — APPROVED** [review]
Looks great Nick!

**Review by paulcpederson — APPROVED** [review]

**Comment by SkyeSeitz** [comment]
Hiyya @nicklu10! Can we update the filled icons name to end in `-f` instead of "filled" or `-f-[size]`?

**Comment by nicklu10** [comment]
@SkyeSeitz yep, good call.

**Comment by SkyeSeitz** [comment]
oops- branch has already been mergey merged. No worries, I actually have to create a branch now for a rush ArcGIS Online request that I would love y'all's eyes on in a few. I can include the `-f` naming correction in my branch and then make a release.

**Comment by nicklu10** [comment]
@SkyeSeitz I just updated keyword.json, go ahead take a look and let me know if it looks good.

**Comment by paulcpederson** [comment]
Sorry about that @SkyeSeitz . The one time I merge a pr...

**Comment by SkyeSeitz** [comment]
😂😂 We were ships passing in the night. No worries at all. Thanks, as always, for your eyes on these!

**Pull request merged**
