### PR TITLE
#107 - remove filled/outlined concept entirely

### PR DESCRIPTION
**Pull request by paulcpederson**
- Icons no longer have `filled` and `outline` properties. Each icon in the json file has sizes. 
- Docs no longer have a filled toggle
- All icons + variants display on the docs site at the same time
- Cleaned all the old filled icons' js and ts files that were still in the repo.

I've retained the naming structure of the JS/TS files for backwards compatibility in the cases where there is still in fact a filled icon variant for that style.

Though we now treat the filled variants as their own icon in terms of what we output, I automatically copy the alias, keyword, and version data from their non-filled counterpart.

### CODE REVIEW

**Comment by paulcpederson** [comment]
@julio8a @johnmgriffith I've added the ability to store multipath icons with opacity data in the main icons folder. I've tried this out with one of the sample icons (ImageryLayer) and it looks really good. 

Screen Shot 2020-04-03 at 4 38 09 PM

I didn't commit any changes to the icon folder, but after this we can add them and run a build :+1:

I also added a pointer to the calcite-components icon component for some cross-polination.

**Comment by paulcpederson** [comment]
I should mention that most of the deleted files are older filled variants from the `js` folder that are now gone. We never actually removed them back when we got rid of filled initiallly...

**Comment by julio8a** [comment]
Great!

**Comment by johnmgriffith** [comment]
Looks good to me! Only thing I noticed was that when I ran the branch locally, the 16px sprite detected changes. Was a 16px icon recently updated?

**Comment by paulcpederson** [comment]
@johnmgriffith updated

**Comment by johnmgriffith** [comment]
Cool thanks!

**Pull request merged**
