### PR TITLE
#105 - don't go to top on close of modal

### PR DESCRIPTION
**Pull request by paulcpederson**

### CODE REVIEW

**Comment by johnmgriffith** [comment]
Great!! Can we also get this update on the Meridian repo?

**Comment by paulcpederson** [comment]
you mean like this: https://github.com/ArcGIS/calcite-meridian-icons/pull/5 ? 😉

**Comment by johnmgriffith** [comment]
Haha yes exactly :D

**Comment by johnmgriffith** [comment]
When I run this locally, I see that the release number went back to 3.0.0, even though now it's 3.0.2. Is that a problem with this branch?

**Comment by paulcpederson** [comment]
let me make sure this branch is up-to-date with `master`

**Comment by paulcpederson** [comment]
I think it would have been ok to merge, but should be up to date with `master` now

**Comment by johnmgriffith** [comment]
Okay, sounds good

**Comment by KatelynSeitz** [comment]
Heyyo! thanks, @paulcpederson

**Pull request merged**
