### PR TITLE
Documentation Updates

### PR DESCRIPTION
**Pull request by paulcpederson**
- sticky bar for search input + filled toggle
- name of icons displayed
- update aliases/categories with latest
- use new search icon in search input
- automatically rebuild the json file when icons are added/updated (also will automatically refresh the page)

<strike>*Note*: though the icon definitions file will be updated automatically, new svg icons that are added after the server is already running won't be run through svgo. Make sure before you publish a new release you run the script as you did before to ensure all icons are optimized before release.</strike>

### CODE REVIEW

**Comment by paulcpederson** [comment]
no they are not optimized if you add them _after_ the server is already running. If you add them to the folder _before_ the server is running they will be optimized. We can probably figure out a way to optimize them as they come in, but it was causing a feedback loop of updates:

```
icon added => change detected => run optimize => change detected => run optimize ...
```

I'll have to rewrite some stuff to get that working properly, but it's possible.

**Comment by johnmgriffith** [comment]
I noticed a bug… if I make an edit like renaming/adding/deleting an icon, then I lose the ability to click on icons and trigger the modal dialogue box. It simply stays put, like this:

image

**Comment by paulcpederson** [comment]
hmm, will investigate. Heading out for the night but can check into it in the AM

**Comment by paulcpederson** [comment]
@johnmgriffith ok, pushed an update. Icons are automatically optimized as they're added and the doc site will not error if icons are renamed/deleted, now.

**Pull request merged**
