### PR TITLE
1.6.5

### PR DESCRIPTION
**Pull request by KatelynSeitz**
added `send` icon and three `view` icons to replace `eye` and `hide`.

### CODE REVIEW

**Comment by johnmgriffith** [comment]
We'll need to update the icon "layer-hide" as well. It also has the eye in it.

**Comment by paulcpederson** [comment]
@KatelynSeitz the indentation in keywords.json is pretty wacky right now too, if you're making changes could you look at that as well?

**Comment by KatelynSeitz** [comment]
@johnmgriffith @paulcpederson I have added updates for two existing eye icons and cleaned up the keywords.json file.

**Comment by johnmgriffith** [comment]
The new icons look great!

**Pull request merged**
