### PR TITLE
Paulcpederson/3.0.0

### PR DESCRIPTION
**Pull request by paulcpederson**
filters out bounding box from js data, converts ellipse/circle to path

### CODE REVIEW

**Comment by johnmgriffith** [comment]
This is looking great! Is there any way to keep the opacity data as well for the multi-value icons?

**Comment by paulcpederson** [comment]
yeah, clearly this is just part of the solution, but wanted to get it in in case you have another dev you want to help you

**Comment by johnmgriffith** [comment]
Perfect, thanks. Would you prefer to merge this now then, and have the opacity problem solved in another PR?

**Comment by paulcpederson** [comment]
yes

**Pull request merged**
