### PR TITLE
v3.29.1

### PR DESCRIPTION
**Pull request by arowles**
**added**

close-caption-16
close-caption-24
close-caption-32

close-caption-f-16
close-caption-f-24
close-caption-f-32

transcript-16
transcript-24
transcript-32

transcript-f-16
transcript-f-24
transcript-f-32

image

image

### CODE REVIEW

**Comment by paulcpederson** [comment]
Icons appear to be blank/all black

**Comment by arowles** [comment]
Not sure why since all the icons looked good upon launching the reference page.

**Review by jorgegutierrez2019 — COMMENTED** [review]
they look all black to me also

**Comment by paulcpederson** [comment]
@arowles the `fill` attribute is missing for the bounding rectangle path. So it's going to default to a black fill. Other icons set this fill to ` fill="none"`

**Pull request closed without merging**
