### PR TITLE
3.24.6

### PR DESCRIPTION
**Pull request by aphilobos**
**Added**

box-chart-series 
break-recurrence 
configure-grid-unit 
dimensions-unit 
dimensions-wall 
flip-vertical 
merge-details 
merge-units 
polygon-select
split-units

25_Indoors_screenshot

10_Charts_and_Graphs_screenshot

### CODE REVIEW

**Review by allieorth — APPROVED** [review]
Looks good — we discussed the potential issues with adding another product specific category but decided to keep things as they are currently, especially with the rush timeline. 
Ship it!

**Comment by nel11211** [comment]
These will be available as part of 1.9.0 correct?

**Comment by SkyeSeitz** [comment]
> These will be available as part of 1.9.0 correct?

Yes, these will be included in Oct 2nd's 1.9.0 release 👍🏽

**Comment by nel11211** [comment]
> > These will be available as part of 1.9.0 correct?
> 
> Yes, these will be included in Oct 2nd's 1.9.0 release 👍🏽

Not seeing the new icons on 1.9.0. Also don't see any mention in the [changelog](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/CHANGELOG.md#changelog). Will these come through in a follow-up patch?

Here's a codepen attempting to use the new icons:
https://codepen.io/nel11211/pen/poqOXMq?editors=1000

**Comment by paulcpederson** [comment]
looks like clacite just bumped this a couple hours ago, not sure their release plans https://github.com/Esri/calcite-design-system/pull/7925

**Comment by geospatialem** [comment]
@nel11211 Added [`3.24.7`](https://github.com/Esri/calcite-ui-icons/pull/307) via https://github.com/Esri/calcite-design-system/pull/7949 to today's maintenance release. cc @paulcpederson

**Pull request merged**
