### PR TITLE
1.6.6

### PR DESCRIPTION
**Pull request by KatelynSeitz**
updated `popup` and `configure-popup`.

### CODE REVIEW

**Comment by paulcpederson** [comment]
We need to run the optimize task on these to remove the id's. Also, why use 644 file permissions on the images?

**Comment by johnmgriffith** [comment]
We've never removed the ID's in our process before, didn't think that was an issue. Also, not sure what you mean by the 644 permissions. We are doing everything the same as we usually do it.

**Comment by paulcpederson** [comment]
`npm run optimize` will remove the ids. It's important for web pages that use more than icon in the page inline as it's invalid html.

**Comment by paulcpederson** [comment]
👍 Thanks, looks good!

**Comment by paulcpederson** [comment]
published on npm this AM

**Pull request merged**
