### PR TITLE
Fix casing of color correction JS files.

### PR DESCRIPTION
**Pull request by jcfranco**
The lowercased files were causing build errors in case-sensitive environments.

```
[ ERROR ]  Rollup: Unresolved Import
           Could not resolve './js/colorCorrection16.js' from
           node_modules/@esri/calcite-ui-icons/index.js
```

☝️ from https://travis-ci.com/Esri/calcite-app-components/builds/133112706

**Note**: I'm not sure if these files are generated, so please let me know if there's another place I need to update.

### CODE REVIEW

**Comment by jcfranco** [comment]
+@johnmgriffith

**Comment by paulcpederson** [comment]
@jcfranco they are generated, yeah. Let me take a look.

**Comment by paulcpederson** [comment]
Maybe just a problem with this camelCase library? It's used here: https://github.com/Esri/calcite-ui-icons/blob/master/bin/path-data.js#L92

**Comment by paulcpederson** [comment]
seems like the script produces the correct casing, Im not sure how they got lowercased, when I delete them and run optimize again all is well, so I think this pr should solve the problem, thanks @jcfranco

**Comment by jcfranco** [comment]
@paulcpederson No problem! Is there someone else who can do the merge? I don't have power in this repo. 😅

**Comment by paulcpederson** [comment]
🏄

**Comment by jcfranco** [comment]
Awesome, thanks! When's the next NPM publish?

**Comment by paulcpederson** [comment]
two minutes ago 😄

**Comment by jcfranco** [comment]
Sweet, thanks again! 🥇

**Pull request merged**
