### PR TITLE
1.2.0

### PR DESCRIPTION
**Pull request by KatelynSeitz**
**Added to GIS** 

•  hillshade-effect
• compass-needle

screen shot 2018-08-29 at 4 42 31 pm
____________

**Added to Generic**
• transparency

screen shot 2018-08-29 at 4 43 04 pm

____________

**Added to Text**
•gamma

screen shot 2018-08-29 at 4 42 18 pm

____________

This branch resolves issue #18

### CODE REVIEW

**Comment by johnmgriffith** [comment]
Looks good!

**Comment by johnmgriffith** [comment]
@asangma @julio8a Because we also have `compass-north-circle`, we need to create a pattern which establishes which compass to use in certain circumstances… sometimes `compass-north-circle` is better, other times `compass-needle` will be better.

**Comment by asangma** [comment]
> we need to create a pattern which establishes which compass to use in certain circumstances

Agreed.
Feel free to spin up an issue/discussion. We can probably extract a fair bit from current usage.

**Comment by asangma** [comment]
@johnmgriffith I did not see a `compass-needle-[size]-f.svg`. Is that in the works?

**Comment by johnmgriffith** [comment]
Julio said that unless there is a structural or process change, it's unnecessary to add him as a reviewer. We should be good to merge and release now.

**Comment by johnmgriffith** [comment]
@asangma yes, under Files Changed tab, we've got the `compass-needle-32-f` and other sizes there. The top part of the needle is filled in on those assets.

**Comment by asangma** [comment]
Got it. Sorry...must have missed it. 👍

**Pull request merged**
