### PR TITLE
3.2.0

### PR DESCRIPTION
**Pull request by nicklu10**

### CODE REVIEW

**Comment by paulcpederson** [comment]
Feel free to merge.

**Comment by nicklu10** [comment]
@paulcpederson added tags to the keywords to the json file.

**Comment by nicklu10** [comment]
@paulcpederson I can't seem to get these icons named x-axis-guide and y-axis-guide to show up on the reference page. They are in the icons folder and tagged correctly. Can you check to see if you find an issue? thanks!

**Comment by paulcpederson** [comment]
remove the `id` attributes and clean up the svg and if that doesn't work I can take a look

**Comment by KatelynSeitz** [comment]
Hmmm the SVGs had already been optimized and ids get removed in the optimization when we launch the reference page, but I went ahead and optimized again, but no change. 

Also another strange thing I am seeing is the cards, when clicked, do not activate a pop up to show the three icon sizes anymore.

**Comment by paulcpederson** [comment]
You had a space in `line-solid-24 .svg`, I've pushed a correction.

**Comment by KatelynSeitz** [comment]
🎉🎉🎉 thank you @paulcpederson! ok looks good to merge now.

**Pull request merged**
