### PR TITLE
1.7.0

### PR DESCRIPTION
**Pull request by KatelynSeitz**
added three new icons.

### CODE REVIEW

**Comment by paulcpederson** [comment]
looks good, the indentation in `docs/keywords.json` is a bit strange, though.

**Comment by johnmgriffith** [comment]
There were some conflicts that needed to be resolved, so I corrected the conflicts and updated the icons.json file when I launched the reference page locally.

**Comment by KatelynSeitz** [comment]
@paulcpederson `docs/keywords.json` should be solved if you want to do one more review.

**Comment by paulcpederson** [comment]
published on npm @ 1.7.0

**Pull request merged**
